name: notredame
description: The 4th generation of ÉTSMobile, the main gateway between the École de technologie supérieure and its students on mobile devices.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.62.4

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  get_it: ^8.2.0
  provider: ^6.1.5
  stacked: ^3.5.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.6
  firebase_remote_config: ^6.0.0

  # Web
  url_launcher: ^6.3.2

  # Utils
  logger: ^2.6.1
  fluttertoast: ^9.0.0

  # Widgets
  table_calendar: ^3.2.0
  auto_size_text: ^3.0.0
  gpt_markdown: ^1.1.2

  # Animations
  skeletonizer: ^2.0.1+1
  animations: ^2.1.0

  # Google
  shared_preferences: ^2.5.3

  # flutter community
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.12.0
  share_plus: ^12.0.1

  # Other
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^10.0.0
  github: ^9.25.0
  in_app_review: ^2.0.11
  timeago: ^3.7.1
  calendar_view: ^1.4.0
  reorderable_grid_view: ^2.2.8
  infinite_scroll_pagination: ^5.1.1
  device_calendar: ^4.3.3
  http: ^1.5.0
  xml: ^6.6.1
  collection: ^1.19.1
  intl: ^0.20.2
  msal_auth: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.6.0
  import_sorter: ^4.6.0
  flutter_lints: ^6.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: 'LaunchImage'
  image_path: 'assets/icons/launcher_icon.png'
  adaptive_icon_background: '#EF3F45'
  adaptive_icon_foreground: 'assets/icons/ic_launcher_foreground.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/markdown/
    - assets/icons/
    - assets/animations/
    - assets/certificates/
    - assets/
